//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosmetic.DataModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModulesOnRole
    {
        public string Id { get; set; }
        public string RoleId { get; set; }
        public string ModulesId { get; set; }
        public bool IsView { get; set; }
        public bool IsAction { get; set; }
        public bool Status { get; set; }
        public bool Active { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Role Role { get; set; }
    }
}
